### ISSUE TITLE
Specifying port on command line does not appear to work

### ISSUE THREAD

**Issue by rterbush** [yogthos/instant-pdf#4]
Specifying a port number to listen on as the doc suggests logs the following error.
```
Nov 20 02:30:42 ip-10-1-2-53 java: Exception in thread "main" clojure.lang.ArityException: Wrong number of args (1) passed to: main/-main
```

**Comment by yogthos** [comment]
ah my bad, looks like `lein-ring` doesn't generate a main that accepts a port. You have to specify it as an environment variable instead:

```
export PORT=3001
java -jar instant-pdf.jar
```

I've updated the docs to reflect this.
