### ISSUE TITLE
support border-color for table and cell

### ISSUE THREAD

**Issue by Shiftane** [yogthos/instant-pdf#6]
First thanks for this project.
Is that possible to have the border-color for table and cells ?
Thanks a lot

**Comment by yogthos** [comment]
Hi, it's not supported at the moment. I'd have to take a look at adding that in the clj-pdf library.

**Comment by Shiftane** [comment]
Hi, clj-pdf support :border-color for cell, could be a first step.

**Comment by yogthos** [comment]
Actually looks like you should be able to use `border-color` on pdf-table elements in clj-pdf already. I'll bump up the dependency to the latest version.

**Comment by Shiftane** [comment]
I use your service on mashape and it's not working for the moment

**Comment by yogthos** [comment]
The mashape version of the service is using an older version of clj-pdf. I just updated the libraries, and this now works as expected:

```javascript
[{"title":"My document"},
["pdf-table",
{"border-color": [200,0,0]},
[10,10,10], 
[["pdf-cell",
  {"border-color": [0,200,0]}, "foo"],
 ["pdf-cell", "foo"],
 ["pdf-cell", "foo"]]]]
```

**Comment by yogthos** [comment]
just pushed out a new version to heroku, let me know if it works as expected

**Comment by yogthos** [comment]
seems to work in my testing, so I'm going to close this one
